apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-middle-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-middle
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-middle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-middle
spec:
  selector:
    matchLabels:
      app: mysql-middle
  template:
    metadata:
      labels:
        app: mysql-middle
    spec:
      containers:
        - name: mysql
          image: mariadb:10.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: local
            - name: MYSQL_USER
              value: testuser
            - name: MYSQL_PASSWORD
              value: testpassword
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-sql
          configMap:
            name: mysql-middle-init