apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-first-init
data:
  init.sql: |
    -- api_first initial schema
    CREATE TABLE invoices (
      id INT AUTO_INCREMENT PRIMARY KEY,
      company_name VARCHAR(255),
      invoice_id VARCHAR(100),
      invoice_data TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- company table (new)
    CREATE TABLE company (
      id INT AUTO_INCREMENT PRIMARY KEY,
      company_name VARCHAR(255)
    );

    -- logs
    CREATE TABLE api_logs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      level VARCHAR(20),
      message TEXT,
      context JSON,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );